name: "transelemental.com"
description: "Transelemental"

url: "http://transelemental.com"
baseurl: "/Transelemental"

markdown: rdiscount
permalink: /:categories/:title
pygments: true


gems:
  - jekyll-redirect-from